; PlatformIO Project Configuration File
;
; M5Stack Basic + M5Stack GNSS Module
; EKF Altitude Fusion: GNSS + BMP280 + BMI270

[env:m5stack-core-esp32-16M]
platform  = espressif32
board     = m5stack-core-esp32-16M
framework = arduino
monitor_speed    = 115200
monitor_filters  = esp32_exception_decoder
build_flags      = -DCORE_DEBUG_LEVEL=0
                   -fpermissive
lib_deps =
    m5stack/M5Unified @ ^0.2.13
    mikalhart/TinyGPSPlus @ ^1.1.0